version: '3'

services: 
    app:        
        build: .
        entrypoint: .docker/entrypoint.sh  
        ports:
          - "3000:3000"
        volumes:
          - .:/home/node/app          
        depends_on:
          - database

    database:
        build: .docker/postgres      
        container_name: postgres
        restart: always        
        ports:
          - "5432:5432"         
        environment: 
            POSTGRES_DB: crud            
            POSTGRES_PASSWORD: 123456         
               