version: '3'

services: 
    api:
        container_name: crud
        build: .
        entrypoint: ./.docker/entrypoint.sh
        ports: 
            - "${API_PORT}:${API_PORT}"
        volumes: 
            - .:/home/api
            - /home/api/node_modules
        depends_on:
          - database

    database:
        container_name: postgres
        image: postgres
        environment: 
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}           
        ports:
            - "${DB_PORT}:${DB_PORT}"        